import platform
import sys

SYS_VER = int(platform.release())
NEWER_SYS_VER = SYS_VER >= 10  # win10以上版本
if getattr(sys, "frozen", False):  # 如果是编译环境
    NEWER_VER = NEWER_SYS_VER
else:
    # print("编译环境")
    NEWER_VER = (sys.version_info >= (3, 8))


class Strings:
    REMOTE_SETTING_JSON_GITEE = 'https://gitee.com/wfql1024/MultiWeChatManager/raw/master/remote_configs/remote_setting_v7'
    REMOTE_SETTING_JSON_GITHUB = 'https://raw.githubusercontent.com/wfql1024/MultiWeChatManager/master/remote_configs/remote_setting_v7'
    VIDEO_TUTORIAL_LINK = "https://www.bilibili.com/video/BV174H1eBE9r"

    DEFAULT_AVATAR_BASE64 = "/9j/4AAQSkZJRgABAQEAAAAAAAD/4QAuRXhpZgAATU0AKgAAAAgAAkAAAAMAAAABAAAAAEABAAEAAAABAAAAAAAAAAD/2wBDAAoHBwkHBgoJCAkLCwoMDxkQDw4ODx4WFxIZJCAmJSMgIyIoLTkwKCo2KyIjMkQyNjs9QEBAJjBGS0U+Sjk/QD3/2wBDAQsLCw8NDx0QEB09KSMpPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT3/wAARCAHaAdoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD1xnbJ5pNzetD9TSUALub1o3N60lFAC7m9aNzetJRQAu5vWjc3rSUUALub1o3N60lFAC7m9aNzetJRQAu5vWjc3rSUUALub1o3N60lFAC7m9aNzetJRQAu5vWjc3rSUUALub1o3N60lFAC7m9aNzetJRQAu5vWjc3rSUUALub1o3N60lFAC7m9aNzetJRQAu5vWjc3rSUUALub1o3N60lFAC7m9aNzetJRQAu5vWjc3rSUUALub1o3N60lFAC7m9aNzetJRQAu5vWjc3rSUUALub1o3N60lFAC7m9aNzetJRQAu5vWjc3rSUUALub1o3N60lFAC7m9aNzetJRQAu5vWjc3rSUUALub1o3N60lFAC7m9am3N61BU1AET9TSUr9TSUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABU1Q1NQBE/U0lK/U0lABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVNUNTUARP1NJSv1NJQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFTVDU1AET9TSUr9TSUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABU1Q1NQBE/U0lK/U0lABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVNUNTUARP1NJSv1NJQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFTVDU1AET9TSUr9TSUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUVVmvFj4B5BwaALDyKnU4qCS7QfdYVnyXLyNyeO1QUAaBv27EVH/aUvt+VU6KAL41F+5FTR3qn7zCsqigDdSZG+62afWHHM0f3TV63vgcB2oAvUUgcOAR3paACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKmqGpqAIn6mkpX6mkoAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiqt5cBEKjrj1oAZdXWMquQQazXcuSSc5oclySaSgAooooAKKKKACiiigAoyR0oooAuW14UOGJI6CtNDkA1gVoWVzjIPc45NAGhRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFTVDU1AET9TSUr9TSUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFADZH2IT6DNY9xJ5smeOnar19LsG3P3hWXQAUUUUAFFFFABRRRQAUUUUAFFFFABTkOHU+hptFAG1ay+bHnjrjipqy7GXDhM9TWpQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFTVDU1AET9TSUr9TSUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFB6GikP3T9KAMq+k3uPYVVqWY5eoqACiiigAooooAKKKKACiiigAooooAKKKKAJbc7JlPoa2Yn3oDWEnDg1s2ZzADQBNRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVNUNTUARP1NJSv1NJQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUjfcP0paQ9D9KAMF/vn60lSSDDn61HQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVsWP8Ax6rWQOorZs/+PZaAJqKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACpqhqagCJ+ppKV+ppKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACg9D9KKKAMa5TDioKvajHh1+lUaACiiigAooooAKKKKACiiigAooooAKKKKAHxDMgHvWzbjEIFZNquZ0+tbKDAxQAtFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABU1Q1NQBE/U0lK/U0lABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBWvIt6E+grIrfcZBHqMVlXluY3JAOMdaAKtFFFABRRRQAUUUUAFFFFABRRRQAUUVLDG0jjAOM80AW7CLIDnsfStCmRRiNMCn0AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABU1Q1NQBE/U0lK/U0lABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVFcRCSMjHJqWigDDljMblT2qOtW7tg6EgDJPWstwUJB7HFACUUUUAFFFFABRRRQAUUUUAKBk1qWdv5YJI68iobO2ycsAQRxWiBgCgAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACpqhqagCJ+ppKV+ppKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooACAayr2LYS3qa1ap6iMxj60AZdFFFABRRRQAUUUUAFS28fmSYqKrmnD99n2oA0o0CIB7U6iigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACpqhqagCJ+ppKV+ppKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKpai48sAdc1alkWNMmsm5mMjnk4zxQBBRRRQAUUUUAFFFFABVuwfE2D0xVSnxuYzkHFAG7RUNtMsoA5yBzmpqACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKmqGpqAIn6mkpX6mkoAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKY8qp3H50APqGa4WIHvj0qpNfE5AHUY4NU3dmPJNAEk1yZScEgE9KgoooAKKKKACiiigAooooAKKKKAJI5WjPBNaVveLJgY9uayaUEjoaAN/I9aKyYbxo8AjPPc1oxXCyAZIBPbNAEtFGQaKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACpqhqagCJ+ppKV+ppKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoopCcdaAFpryKn3jiq016iZAJzjjiqMty8mctwaALc99jOwqaoyStIcn1zxUdFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUqOUORSUUAX4b5hgNtAAq7HMknRgaw6kjneP7pxQBuUVRhvh0djnPHFXEkVxkUAOooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACpqhqagCJ+ppKV+ppKACiiigAooooAKKKKACiiigAooooAKKKKACignFU7m8CZUDPvQBYluFiGTzzjis2a8Z/ulh+NQSSM5JyeTTKAFJJ6nNJRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFTxXLRkZZsemagooA17e6WTAwc4zzVkHNYAJHQ1etrzHBHtyaANGikDg9CKWgAooooAKKKKACiiigAooooAKKKKACiiigAqaoamoAifqaSlfqaSgAooooAKKKKACiiigAooooAKKKKACiiigCpezbAV45FZZJJyat6l/r/wAKp0AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBfsrgj5Tjk1o1iW/wDrk+tbdABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABU1Q1NQBE/U0lK/U0lABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAGXqX+vH0qnVzUgfPz7VToAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigB8H+uT61u1iW4PnL9a26ACiiigAooooAKKKKACiiigAooooAKKKKACpqhqagCJ+ppKV+ppKACiiigAooooAKKKKACiiigAooooAKKKKAK1zbiQE98YrOe3cHAVj+FbVFAGH5En9xvyo8iT+435VuUUAYfkSf3G/KjyJP7jflW5RQBh+RJ/cb8qPIk/uN+VblFAGH5En9xvyo8iT+435VuUUAYfkSf3G/KjyJP7jflW5RQBh+RJ/cb8qPIk/uN+VblFAGH5En9xvyo8iT+435VuUUAYfkSf3G/KjyJP7jflW5RQBh+RJ/cb8qPIk/uN+VblFAGH5En9xvyo8iT+435VuUUAYfkSf3G/KjyJP7jflW5RQBh+RJ/cb8qPIk/uN+VblFAGH5En9xvyo8iT+435VuUUAYfkSf3G/KlFvJ/cb8q26KAKNra45Ocg5q9RRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVNUNTUARP1NJSv1NJQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFTVDU1AET9TSUr9TSUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABU1Q1NQBE/U0lK/U0lABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVNUNTUARP1NJSv1NJQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFTVDU1AET9TSUr9TSUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABU1Q1NQBE/U0lK/U0lABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVNUNTUARP1NJU3p9BRQBDRU1FAENFTUUAQ0VNRQBDRU1FAENFTUUAQ0VNRQBDRU1FAENFTUUAQ0VNRQBDRU1FAENFTUUAQ0VNRQBDRU1FAENFTUUAQ0VNRQBDRU1FAENFTUUAQ0VNRQBDRU1FAENFTUUAQ0VNRQBDRU1FAENFTUUAQ0VNRQBDRU1FAENFTUUAQ0VNRQBDRU1FAENTUU1vvH60Af/2Q=="

    WARNING_SIGN = "⚠️" if NEWER_VER else "?!"
    SURPRISE_SIGN = "✨" if NEWER_VER else "✦"
    MUTEX_SIGN = "🔒" if NEWER_VER else "⚔"
    CFG_SIGN = "📝" if NEWER_VER else "❐"
    MNG_SIGN = "📝" if NEWER_VER else "☰"
    UNLOCK_CFG_SIGN = "🔓" if NEWER_VER else "⬎"

    REFRESH_HINT = "(标签页单击切换,双击可刷新)"
    TRAY_HINT = "(到托盘)"
    SIDEBAR_HINT = "(侧栏)"

    LOGIN_SETTINGS_INSTRUCTIONS = \
        ("\n- 一键登录前隐藏软件主窗口 (:字面意思)\n"
         "\n- 一键登录前关闭多余登录窗口 (:字面意思)\n"
         "\n- 互斥体选项\n"
         "  > 登录时解锁配置文件 (:不解锁可提高登录速度, 除非权限不够替换配置文件\n"
         "  > 默认有互斥体 (:登录前默认当前所有平台进程都含有互斥体)"
         "  > 立即查杀所有互斥体 (:查杀当前平台的所有进程互斥体和解锁登录配置文件)\n"
         "\n- 调用模式 (:以非管理员身份调用程序, 遇到玄学问题可以试试切换, 但不一定能解决~)\n"
         "\n- 登录按钮\n"
         "  > 自动点击 (:字面意思)\n"
         "  > 添加按钮 (:用于无法自动点击按钮时, 指定登录按钮, 用逗号隔开.)\n")

    PLATFORM_DISABLED_HINTS = {
        "friendly": [
            "空空如也～你还没启用任何平台哦，快去设置里挑几个上线吧！",
            "现在啥平台都不登，我猜你是来看看我长得好不好看。",
            "你把所有平台都关了，是打算放空自我，还是……真的不打算登录？",
            "平台列表静悄悄地躺平了，要不给它们一点上班的机会？",
            "你一个都不启用，我就真的什么都干不了啦！",
        ],
        "sarcastic": [
            "一个平台都不启用，是想让我陪你发呆吗？",
            "真·佛系操作，一个都不登，缘分到了再登录？",
            "你全关了，那你用我，是图我什么？",
            "这……你是登录器终结者吗？",
            "你把平台都关了，是不是还打算让我自动退出？",
        ],
        "motivational": [
            "还没启用平台，快去设置一下吧，精彩内容在等你！",
            "啥都没启用，登录界面好寂寞，快选几个平台热闹一下。",
            "就差你一点小操作，登录世界就开启啦～",
        ]
    }


if __name__ == '__main__':
    print(sys.version_info)
    print(sys.version_info >= (3, 8))
    print(NEWER_VER)
    print(Strings.WARNING_SIGN)
    print(Strings.SURPRISE_SIGN)
    print(Strings.MUTEX_SIGN)
    print(Strings.CFG_SIGN)
